monitor=,preferred,auto,1

#exec-once = waybar
#exec-once = dunst

input {
    kb_layout = us
}

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
}

device{
name=elan1203:00-04f3:307a-touchpad
natural_scroll=true
}

decoration {
    rounding = 10
}

animations {
    enabled = yes
}

bind = SUPER, RETURN, exec, kitty
bind = SUPER, Q, killactive
bind = SUPER, M, exit
bind = SUPER, E, exec, dolphin
#bind = SUPER, D, exec, rofi -show drun

# Toggle floating mode
bind = SUPER, F, togglefloating

# Move floating windows with Super + Left Click
bindm = SUPER, mouse:272, movewindow

# Resize floating windows with Super + Right Click
bindm = SUPER, mouse:273, resizewindow


# Ambxst
source = ~/.local/share/ambxst/hyprland.conf

# OVERRIDES
# Down here you can write or source anything that you want to override from Ambxst's settings.
